[tool.poetry]
name = "model"
version = "0.1.0"
description = ""
authors = ["ThickNavyRain <15817473+thicknavyrain@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
tqdm = "^4.67.1"
marimo = "^0.13.2"
matplotlib = "^3.10.1"
scipy = "^1.15.2"
statsmodels = "^0.14.4"
openpyxl = "^3.1.5"
missingno = "^0.5.2"
setuptools = "^80.0.1"
scikit-learn = "^1.6.1"
xgboost = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
